### ISSUE TITLE
AssertionError: Assertion failed.

### ISSUE THREAD

**Issue by GISer-WB** [woodsgao/pytorch_segmentation#1]
Namespace(accumulate=8, adam=False, backend='nccl', batch_size=4, data='/content/data/custom', epochs=100, img_size='512', init_method='tcp://127.0.0.1:23456', local_rank=0, lr=0.001, mp=False, multi_scale=False, nosave=False, notest=False, num_workers=4, rank=0, weights='', world_size=1)
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    nosave=opt.nosave or (opt.local_rank > 0),
  File "train.py", line 46, in train
    train_fetcher = Fetcher(train_loader, train_data.post_fetch_fn)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_modules/utils/fetcher.py", line 17, in __init__
    self.preload()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_modules/utils/fetcher.py", line 27, in preload
    self.batch = next(self.loader_iter)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/My Drive/deep/utils/datasets.py", line 148, in __getitem__
    return self.get_item(idx)
  File "/content/drive/My Drive/deep/utils/datasets.py", line 125, in get_item
    seg = SegmentationMapOnImage(seg, shape=img.shape)
  File "/usr/local/lib/python3.6/dist-packages/imgaug/augmentables/segmaps.py", line 108, in __init__
    ia.do_assert(nb_classes is not None)
  File "/usr/local/lib/python3.6/dist-packages/imgaug/imgaug.py", line 1869, in do_assert
    raise AssertionError(str(message))
AssertionError: Assertion failed.

Hello,could you help me with this problem?Thanks a lot.

**Comment by WoodsGao** [comment]
You can print the length of your dataset and check it.
This may be because your `train.txt` is empty, please execute `split_dataset.py`
